
// I LOVE JAVA
function myFunction() {
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://cadenthelearner.github.io/inconspicuous/", '_blank');
    window.open("https://www.youtube.com/@cadenthepro", '_blank');

        alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("Keep Going");
     alert("BOO!");alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     window.open("https://www.youtube.com/watch?v=Z-LdvL-UGd0", '_blank');
     window.open("https://www.youtube.com/watch?v=Z-LdvL-UGd0", '_blank');
     window.open("https://www.youtube.com/watch?v=Z-LdvL-UGd0", '_blank');
     window.open("https://www.youtube.com/watch?v=Z-LdvL-UGd0", '_blank');

     alert("BOO!");
     alert("BOO!");alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");   alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("Keep Going");
     alert("BOO!");alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     window.open("https://www.youtube.com/watch?v=Z-LdvL-UGd0", '_blank');
     window.open("https://www.youtube.com/watch?v=Z-LdvL-UGd0", '_blank');
     window.open("https://www.youtube.com/watch?v=Z-LdvL-UGd0", '_blank');
     window.open("https://www.youtube.com/watch?v=Z-LdvL-UGd0", '_blank');

     alert("BOO!");
     alert("BOO!");
     alert("BOO!");alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");   
      window.open("https://www.youtube.com/@cadenthepro", '_blank');
     alert("BOO!");alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");alert("BOO!");
     alert("BOO!");
     window.open("https://www.youtube.com/@cadenthepro", '_blank');
     window.open("https://www.youtube.com/@cadenthepro", '_blank');
     window.open("https://www.youtube.com/@cadenthepro", '_blank');
     window.open("https://www.youtube.com/watch?v=Z-LdvL-UGd0", '_blank');
     window.open("https://www.youtube.com/@cadenthepro", '_blank');

     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("Your Still Here?");
      }	
