
// I LOVE JAVA
function myFunction() {
        alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("Keep Going");
     alert("BOO!");alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");   alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("Keep Going");
     alert("BOO!");alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("BOO!");
     alert("Your Still Here?");
      }	
